# Travis CI credentials

language: scala

sudo: false

services:
  - cassandra

scala:
 - "2.10.5"
 - "2.11.7"

env:
  matrix:
    

# Emails to notify
notifications:
  slack:
    - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
    - dev@websudos.co.uk

# Branches to build.
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk7
  - oraclejdk8

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate coveralls

after_success:
  - ./build/publish_develop.sh

