# Travis CI credentials

language: scala

scala:
 - "2.10.4"
 - "2.11.5"

services:
  - cassandra

# Emails to notify
notifications:
  slack:
    - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
    - dev@websudos.co.uk

# Branches to build.
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk7
  - openjdk7

before-script:
  //- rm phantom-dsl/src/main/resources/

script:
  - sbt clean coverage test &&
    sbt coverageAggregate

after_success:
  - sbt coveralls

