# Travis CI credentials

language: scala

scala: 
 - "2.10.0"

# Emails to notify
notifications:
  email:
    - dev@newzly.com

# Branches to build.
branches:
  only:
    - master
    - develop

services:
 - cassandra

script: "./scripts/run_tests.sh"
