# Travis CI credentials

language: scala

scala:
 - "2.10.4"

# Emails to notify
notifications:
  email:
    - dev@newzly.com

# Branches to build.
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk7
  - openjdk7

before_script: "./scripts/test_util.sh"
script: "./scripts/run_tests.sh"
